### ISSUE TITLE
wasm_bindgen/wasm-pack is not supported?

### ISSUE THREAD

**Issue by xxshady** [mtolmacs/wasm2map#26]
https://github.com/rustwasm/wasm-bindgen/issues/3698#issuecomment-2313247387

**Comment by xxshady** [comment]
perhaps thats why example in this repository does not use wasm_bindgen?

**Comment by mtolmacs** [comment]
> perhaps thats why [example](https://github.com/mtolmacs/wasm2map/blob/77efd1828f802fc1ec3c326a6a7b02c2251029de/example) in this repository does not use wasm_bindgen?

No, that's just a personal preference because I use that example for debugging and wasm-bindgen creates a ton of extra code which makes it hard to debug the wasm bytecode <-> sourcemap mapping.

As the [answer to your question in the wasm-bindgen repo](https://github.com/rustwasm/wasm-bindgen/issues/3698#issuecomment-2313608799) indicates you have to have DWARF debug symbols present in the .wasm file you are processing with wasm2map. Otherwise it has nothing to work with.

For `wasm-pack` you might want to try [configuring the underlying wasm-bindgen lib to keep the DWARF info](https://github.com/rustwasm/wasm-pack/issues/1351#issuecomment-2100231587) and see if it works for you.

**Comment by xxshady** [comment]
i see, thank you for the reply, who needs it too: https://github.com/rustwasm/wasm-bindgen/issues/3698#issuecomment-2315687521
